# properties for genesis block compatible with bitxorcore signature scheme used in tests
# for proper generation, update following config-network properties:
# - enableVerifiableState = false
# - enableVerifiableReceipts = false

[genesis]

networkIdentifier = testnet
genesisGenerationHashSeed = 57F7DA205008026C776CB6AED843393F04CD458E0AA2D9F1D5F31A402072B2D6
genesisSignerPrivateKey = B59D53B625CC746ECD478FA24F1ABC80B2031EB7DFCD009D5A74ADE615893175

[cpp]

cppFileHeader = ../../HEADER.inc

[output]

cppFile = ../../tests/test/nodeps/data/GenesisMemoryBlockStorage_data.h
binDirectory = ../seed/testnet

[namespaces]

cat = true
cat.currency = true
cat.harvest = true

[namespace>cat]

duration = 0

[tokens]

cat:currency = true
cat:harvest = true

[token>cat:currency]

divisibility = 6
duration = 0
supply = 8'999'999'998'000'000
isTransferable = true
isSupplyMutable = false
isRestrictable = false

[distribution>cat:currency]

TESO3ZTEVYPBXEOK2KVHXCUZTICYUWL4Y5FA6YI = 409'090'909'000'000
TESKIJX4LXHMVAC5GVJZICGDYSPWCE2RAKCH7LA = 409'090'909'000'000
TESOFGYJMCWQLY5MOOXRTW5FDTZOHSSSVI5V4SQ = 409'090'909'000'000
TESJO2MKUNTKXXQXP756ESH2QS36GG5F3FYYLNI = 409'090'909'000'000
TESMO7LBW7JXCIJLFOJDTMLEQI2GMD7YQPGLHPI = 409'090'909'000'000
TESCQ4CKHK3YNJCY66DBBD4LY3GM4UEAWA2SMUY = 409'090'909'000'000
TESCPP5UGEKUSALFXGXRRYDVIF5FWIFSPJMS2NQ = 409'090'909'000'000
TESBIW24LIIBN6EZGQ4ADDPXQJJH3SCCCHKB6EA = 409'090'909'000'000
TESEZP52DJ2AEASYVWVZNFNUVFWDFK2OQKDKHRQ = 409'090'909'000'000
TESAXE4XR3MIZV42ACYTUQFTKGLJE7ID5KA7RZY = 409'090'909'000'000
TESNFZW5GNZR6NPD36FEQXIVT34PSMDFQ537IOA = 409'090'909'000'000

TESLQGNASJNFJ2HFA3BCF7ACS5ZXMNCDLTOYERY = 409'090'909'000'000
TESIIKDSH7BW7D7LXXBZTSX6HME5NNECA47YN6Q = 409'090'909'000'000
TESC7YNN73KDB3XCDVHS7PI7JNWG22ACT3D4EPI = 409'090'909'000'000
TESAP7PEPYSBAFC4RYDRPDS4ZSA5VITKLQGEBYQ = 409'090'909'000'000
TESCNSOLK7XSY5ANPFWM3OWQQKERUSEMTYQTGHI = 409'090'909'000'000
TESDID55G6SQ5BMTE2PECINL23UEN4WLWEJ6TBY = 409'090'909'000'000
TESKZQ27BTRTOOJEDGVWQAN5NRVBIC4A2XK2YRA = 409'090'909'000'000
TESDDKKM5PFHP27DQE7ROO23W7BWPQHYHSPHQSA = 409'090'909'000'000
TESJMIDNYHCXUWQOMMAY3M4KCYPOBYNYGCABQUQ = 409'090'909'000'000
TESGEKEZP72ZTCNA6ENCRO5Q4SVCZ3HZQMXJXPQ = 409'090'909'000'000
TESLVYFGG2GNTLWVAWO6HF5POAJL4OWPDSKHL6I = 409'090'909'000'000

[token>cat:harvest]

divisibility = 3
duration = 0
supply = 17'000'000
isTransferable = true
isSupplyMutable = true
isRestrictable = false

[distribution>cat:harvest]

TESO3ZTEVYPBXEOK2KVHXCUZTICYUWL4Y5FA6YI = 1'000'000
TESKIJX4LXHMVAC5GVJZICGDYSPWCE2RAKCH7LA = 1'000'000
TESOFGYJMCWQLY5MOOXRTW5FDTZOHSSSVI5V4SQ = 1'000'000
TESJO2MKUNTKXXQXP756ESH2QS36GG5F3FYYLNI = 1'000'000
TESMO7LBW7JXCIJLFOJDTMLEQI2GMD7YQPGLHPI = 4'000'000
TESCQ4CKHK3YNJCY66DBBD4LY3GM4UEAWA2SMUY = 1'000'000
TESCPP5UGEKUSALFXGXRRYDVIF5FWIFSPJMS2NQ = 1'000'000
TESBIW24LIIBN6EZGQ4ADDPXQJJH3SCCCHKB6EA = 1'000'000
TESEZP52DJ2AEASYVWVZNFNUVFWDFK2OQKDKHRQ = 1'000'000
TESAXE4XR3MIZV42ACYTUQFTKGLJE7ID5KA7RZY = 1'000'000
TESNFZW5GNZR6NPD36FEQXIVT34PSMDFQ537IOA = 4'000'000

# additional transactions are appended after generated transactions
# transactions will be sorted based on file names

[transactions]

transactionsDirectory = ../txes

